version: '3'
services: 
    app:
        build: .
        tty: true
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes: 
            - .:/go/src/github.com/ho2ri2s/golang-dialy/